### ISSUE TITLE
find terms of service and privacy policy generator

### ISSUE THREAD

**Issue by kareniel** [TokenBB/meta#2]
alternative is to build it but something probably exists out there.
we want the plugin to generate customized documents on install.

also, what info do we need from the user? name and address?
does it matter what country they live in?
etc

cc @RenaudGagne

**Comment by RenaudGagne** [comment]
do you mean that we should have terms of service and privacy policy generator for each time the plugin in installed or do we want to for ourselves?

I already used a free privacy policy and terms of service generator for tokenbb.io
https://tokenbb.io/privacy-policy/
https://tokenbb.io/terms

Are they unsufficient?

**Comment by kareniel** [comment]
oh that's great!

yeah i'd package a standard set of documents with the plugin. then the user could be able to disable them if they already have some or if they wish to have different ones.

we need something that also covers the user system (signing up, logging in)

we'll also need a set of documents for the plugin itself.

**Comment by RenaudGagne** [comment]
I've check and BBpress doesnt provide any of them to the people who install the plugin. We could be liable for providing erroneous/out of date terms and policies. I think we should make clear on our own policies that we are not responsible for how our users use this plugin and that they are responsible for having their own privacy policy/terms on their own property (website).

**Comment by kareniel** [comment]
works for me!

**Comment by RenaudGagne** [comment]
Can you assign me to this task?

**Comment by RenaudGagne** [comment]
This is the privacy policy for tokenbb.io and does not extend to website who install our plugin (see in terms). Seems plenty good for me.

`<h1>Privacy Policy</h1>


<p>Effective date: August 16, 2018</p>


<p>TokenBB ("us", "we", or "our") operates the https://tokenbb.io website (hereinafter referred to as the "Service").</p>

<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. This Privacy Policy  for TokenBB is powered by <a href="https://privacypolicies.com/free-privacy-policy-generator/">PrivacyPolicies.com</a>.</p>

<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://tokenbb.io</p>

<p>Once you install the TokenBB plugin on your personal website, you are responsible for providing your own privacy policy and terms of services to your users.</p>

<h2>Information Collection And Use</h2>

<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

<h3>Types of Data Collected</h3>

<h4>Personal Data</h4>

<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

<ul>
<li>Email address</li><li>First name and last name</li><li>Cookies and Usage Data</li>
</ul>

<h4>Usage Data</h4>

<p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

<h4>Tracking & Cookies Data</h4>
<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
<p>Examples of Cookies we use:</p>
<ul>
    <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
    <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
    <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
</ul>

<h2>Use of Data</h2>
    
<p>TokenBB uses the collected data for various purposes:</p>    
<ul>
    <li>To provide and maintain the Service</li>
    <li>To notify you about changes to our Service</li>
    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
    <li>To provide customer care and support</li>
    <li>To provide analysis or valuable information so that we can improve the Service</li>
    <li>To monitor the usage of the Service</li>
    <li>To detect, prevent and address technical issues</li>
</ul>

<h2>Transfer Of Data</h2>
<p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
<p>If you are located outside Canada and choose to provide information to us, please note that we transfer the data, including Personal Data, to Canada and process it there.</p>
<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
<p>TokenBB will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

<h2>Disclosure Of Data</h2>

<h3>Legal Requirements</h3>
<p>TokenBB may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
    <li>To comply with a legal obligation</li>
    <li>To protect and defend the rights or property of TokenBB</li>
    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
    <li>To protect the personal safety of users of the Service or the public</li>
    <li>To protect against legal liability</li>
</ul>

<h2>Security Of Data</h2>
<p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

<h2>Service Providers</h2>
<p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

<h3>Analytics</h3>
<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>    
<ul>
        <li>
        <p><strong>Google Analytics</strong></p>
        <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
        <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>                <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p>
    </li>
                            </ul>


<h2>Links To Other Sites</h2>
<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>


<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 18 ("Children").</p>
<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


<h2>Changes To This Privacy Policy</h2>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, please contact us:</p>
<ul>
        <li>By email: tokenbb-io@gmail.com</li></ul>`

**Comment by RenaudGagne** [comment]
Terms of Services:

<h2>TokenBB Terms of Services</h2>
<h3>Philosophy</h3>
We believe software should work with as little configuration as possible. TokenBB is designed to be taking as little time as possible to install so that you can concentrate of what matters most: <strong>build your community.</strong>

We work hard to make sure that every release is in keeping with this philosophy. We ask for as few technical details as possible during the setup process as well as providing full explanations of anything we do ask.
<h3>Personal Responsibility</h3>
When you install TokenBB on your website, it is your responsibility to provide a privacy policy and a terms of services to your users. TokenBB is not responsible for actions taken through or with it's plugin.
<h3>Cookies</h3>
We employ the use of cookies. By using TokenBB's website you consent to the use of cookies in accordance with <a href="https://tokenbb.io/privacy-policy/"><span style="text-decoration: underline;">TokenBB’s privacy policy</span>.</a>

Most of the modern day interactive web sites use cookies to enable us to retrieve user details for each visit. Cookies are used in some areas of our site to enable the functionality of this area and ease of use for those people visiting. Some of our affiliate / advertising partners may also use cookies.
<h3>User Comments</h3>
<ol>
 	<li>Certain parts of this website offer the opportunity for users to post and exchange opinions, information, material and data ('Comments') in areas of the website. TokenBB does not screen, edit, publish or review Comments prior to their appearance on the website and Comments do not reflect the views or opinions of TokenBB, its agents or affiliates. Comments reflect the view and opinion of the person who posts such view or opinion. To the extent permitted by applicable laws TokenBB shall not be responsible or liable for the Comments or for any loss cost, liability, damages or expenses caused and or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</li>
 	<li>TokenBB reserves the right to monitor all Comments and to remove any Comments which it considers in its absolute discretion to be inappropriate, offensive or otherwise in breach of these Terms and Conditions.</li>
 	<li>You warrant and represent that:
<ol>
 	<li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
 	<li>The Comments do not infringe any intellectual property right, including without limitation copyright, patent or trademark, or other proprietary rights of any third party;</li>
 	<li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material or material which is an invasion of privacy</li>
 	<li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
</ol>
</li>
 	<li>You hereby grant to <strong>TokenBB</strong> a non-exclusive royalty-free license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</li>
</ol>
<ol start="2">
 	<li style="list-style-type: none;"></li>
</ol>
We will approve link requests from these organizations if we determine that: (a) the link would not reflect unfavorably on us or our
<h2>Iframes</h2>
Without prior approval and express written permission, you may not create frames around our Web pages or use other techniques that alter in any way the visual presentation or appearance of our Web site.
<h2>Content Liability</h2>
We shall have no responsibility or liability for any content appearing on your Web site. You agree to indemnify and defend us against all claims arising out of or based upon your Website. No link(s) may appear on any page on your Web site or within any context containing content or materials that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.
<h2>Disclaimer</h2>
To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill). Nothing in this disclaimer will:
<ol>
 	<li>limit or exclude our or your liability for death or personal injury resulting from negligence;</li>
 	<li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
 	<li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
 	<li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
</ol>
The limitations and exclusions of liability set out in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer or in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.

To the extent that the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.

&nbsp;
